title = "Bienvenue à la maison"
theme = "story"

## -----------------------------------------------
## Hugo Built-in Features
## -----------------------------------------------

disableKinds = ["taxonomy", "taxonomyTerm", "section"]

## -----------------------------------------------
## Site Parameters
## -----------------------------------------------

[Params]
  description = "Bienvenue à la maison !"
  logo = "images/banner.jpg"
  favicon = true

[Params.social]
  email = "cecilepechin.pro@gmail.com"
  instagram = "https://www.instagram.com/cecile.pechin/"
  airbnb = "https://www.airbnb.fr/rooms/39607525?check_in=2022-09-07&check_out=2022-09-08&guests=1&adults=2&s=67&unique_share_id=7442aa13-b1ad-4706-a27d-a67f282447f8"