title = "Bienvenue à la maison"
theme = "story"

## -----------------------------------------------
## Hugo Built-in Features
## -----------------------------------------------

disableKinds = ["taxonomy", "taxonomyTerm", "section"]

## -----------------------------------------------
## Site Parameters
## -----------------------------------------------

[Params]
  description = "Bienvenue à la maison !"
  logo = "images/banner.jpg"
  favicon = true

[Params.social]
  email = "cecilepechin.pro@gmail.com"
  instagram = "https://www.instagram.com/cecile.pechin/"
  airbnb = "https://www.airbnb.fr/rooms/39607525"